CREATE DATABASE BOARDS;

USE BOARDS;

CREATE TABLE BOARD(
    seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(45) NOT NULL,
    title VARCHAR(45) NOT NULL,
    content VARCHAR(255) NOT NULL,
    password VARCHAR(100) NOT NULL,
    date TIMESTAMP DEFAULT NOW() -- INSERT 시에 DEFAULT로 넣어주면 됨
);

CREATE TABLE COMMENTS(
    CID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(45) NOT NULL, 
    content VARCHAR(100) NOT NULL,
    PASS VARCHAR(100) NOT NULL,
    date TIMESTAMP DEFAULT NOW(),
    seq INT,
    FOREIGN KEY (seq) REFERENCES BOARD(seq) ON DELETE CASCADE
);

-- TEST DATA
INSERT INTO BOARD(nickname, title, content, password, date) VALUES ('ADMIN', '첫 게시글', '안녕하세요 운영자 입니다.', SHA2('1234', 256), DEFAULT);
INSERT INTO COMMENTS(author, content, PASS, date, seq) VALUES ('USER1', '반가워요', SHA2('1234', 256), DEFAULT, 1);