version: '3'
services:
  app:
    image: nodejs_daechu
    container_name: nodejs_daechu
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    command: "npm test"
  db:
    image: mysql_daechu
    container_name: mysql_daechu
    build:
      context: mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE_NAME: "test"
    volumes: 
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
      - "13001:3306"
    #entrypoint: ./mysql/sync_script.sh
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci