version: '3'
services:
  db:
    image: mysql_daechu
    container_name: mysql_daechu
    build:
      context: mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE_NAME: "boards"
    volumes: 
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql-init/:/docker-entrypoint-init.d/
    ports:
      - "13000:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci